// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ToW8Z-GpMh4sucNVfMne3ikHleCa7as',
    appId: '1:826309569862:web:55e4e16cd36d62b6908947',
    messagingSenderId: '826309569862',
    projectId: 'auth-ui-ac80d',
    authDomain: 'auth-ui-ac80d.firebaseapp.com',
    storageBucket: 'auth-ui-ac80d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhmsnrPD8W-yBfLBE3Ta-KGJPbscpwL20',
    appId: '1:826309569862:android:9ee52dcdffd21907908947',
    messagingSenderId: '826309569862',
    projectId: 'auth-ui-ac80d',
    storageBucket: 'auth-ui-ac80d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhy6A8xGEAq8gpTnelTdk4gR903ItNXOI',
    appId: '1:826309569862:ios:07a76d61b986d7bf908947',
    messagingSenderId: '826309569862',
    projectId: 'auth-ui-ac80d',
    storageBucket: 'auth-ui-ac80d.appspot.com',
    iosClientId: '826309569862-k0ikhiqrt5o09i858suhuc9u87bebalp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhy6A8xGEAq8gpTnelTdk4gR903ItNXOI',
    appId: '1:826309569862:ios:07a76d61b986d7bf908947',
    messagingSenderId: '826309569862',
    projectId: 'auth-ui-ac80d',
    storageBucket: 'auth-ui-ac80d.appspot.com',
    iosClientId: '826309569862-k0ikhiqrt5o09i858suhuc9u87bebalp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthUi',
  );
}
